<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="0" failed="3" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-01-13T10:09:51 IST" name="Default suite" finished-at="2022-01-13T10:10:06 IST" duration-ms="14455">
    <groups>
      <group name="5">
        <method signature="ValidateLeadsFunctionality.validateCreateCampaings()[pri:0, instance:com.evs.vtiger.testcases.ValidateLeadsFunctionality@4a7f959b]" name="validateCreateCampaings" class="com.evs.vtiger.testcases.ValidateLeadsFunctionality"/>
      </group> <!-- 5 -->
      <group name="regression">
        <method signature="ValidateLeadsFunctionality.validateCreateLeads()[pri:1, instance:com.evs.vtiger.testcases.ValidateLeadsFunctionality@4a7f959b]" name="validateCreateLeads" class="com.evs.vtiger.testcases.ValidateLeadsFunctionality"/>
      </group> <!-- regression -->
      <group name="6">
        <method signature="ValidateLeadsFunctionality.validateCreateCampaings()[pri:0, instance:com.evs.vtiger.testcases.ValidateLeadsFunctionality@4a7f959b]" name="validateCreateCampaings" class="com.evs.vtiger.testcases.ValidateLeadsFunctionality"/>
      </group> <!-- 6 -->
      <group name="smoke">
        <method signature="ValidateLeadsFunctionality.validateValidLogin(java.lang.String)[pri:0, instance:com.evs.vtiger.testcases.ValidateLeadsFunctionality@4a7f959b]" name="validateValidLogin" class="com.evs.vtiger.testcases.ValidateLeadsFunctionality"/>
        <method signature="ValidateLeadsFunctionality.validateCreateLeads()[pri:1, instance:com.evs.vtiger.testcases.ValidateLeadsFunctionality@4a7f959b]" name="validateCreateLeads" class="com.evs.vtiger.testcases.ValidateLeadsFunctionality"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2022-01-13T10:09:51 IST" name="Default test" finished-at="2022-01-13T10:10:06 IST" duration-ms="14455">
      <class name="com.evs.vtiger.testcases.ValidateLeadsFunctionality">
        <test-method is-config="true" signature="connectDB()[pri:0, instance:com.evs.vtiger.testcases.ValidateLeadsFunctionality@4a7f959b]" started-at="2022-01-13T10:09:51 IST" name="connectDB" finished-at="2022-01-13T10:09:51 IST" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- connectDB -->
        <test-method is-config="true" signature="beforeTestCaseClass()[pri:0, instance:com.evs.vtiger.testcases.ValidateLeadsFunctionality@4a7f959b]" started-at="2022-01-13T10:09:51 IST" name="beforeTestCaseClass" finished-at="2022-01-13T10:09:53 IST" duration-ms="2207" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestCaseClass -->
        <test-method is-config="true" signature="beforeTestCase()[pri:0, instance:com.evs.vtiger.testcases.ValidateLeadsFunctionality@4a7f959b]" started-at="2022-01-13T10:09:53 IST" name="beforeTestCase" finished-at="2022-01-13T10:09:57 IST" duration-ms="3178" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestCase -->
        <test-method signature="abcd()[pri:0, instance:com.evs.vtiger.testcases.ValidateLeadsFunctionality@4a7f959b]" started-at="2022-01-13T10:09:57 IST" name="abcd" finished-at="2022-01-13T10:09:57 IST" duration-ms="12" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [100]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [100]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.evs.vtiger.testcases.ValidateLeadsFunctionality.abcd(ValidateLeadsFunctionality.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- abcd -->
        <test-method is-config="true" signature="afterTestCase()[pri:0, instance:com.evs.vtiger.testcases.ValidateLeadsFunctionality@4a7f959b]" started-at="2022-01-13T10:09:57 IST" name="afterTestCase" finished-at="2022-01-13T10:09:59 IST" duration-ms="2741" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTestCase -->
        <test-method is-config="true" signature="beforeTestCase()[pri:0, instance:com.evs.vtiger.testcases.ValidateLeadsFunctionality@4a7f959b]" started-at="2022-01-13T10:09:59 IST" name="beforeTestCase" finished-at="2022-01-13T10:10:02 IST" duration-ms="2465" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestCase -->
        <test-method signature="validateCreateCampaings()[pri:0, instance:com.evs.vtiger.testcases.ValidateLeadsFunctionality@4a7f959b]" started-at="2022-01-13T10:10:02 IST" name="validateCreateCampaings" finished-at="2022-01-13T10:10:02 IST" duration-ms="600" status="FAIL">
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[no such element: Unable to locate element: {"method":"xpath","selector":"//input[@name='campaignname']"}
  (Session info: chrome=97.0.4692.71)
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
System info: host: 'DESKTOP-O9GK9U1', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 97.0.4692.71, chrome: {chromedriverVersion: 96.0.4664.45 (76e4c1bb2ab46..., userDataDir: C:\Users\DELL\AppData\Local...}, goog:chromeOptions: {debuggerAddress: localhost:57541}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 74f97e7b94944b49846dacbcadffc742
*** Element info: {Using=xpath, value=//input[@name='campaignname']}]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@name='campaignname']"}
  (Session info: chrome=97.0.4692.71)
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
System info: host: 'DESKTOP-O9GK9U1', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 97.0.4692.71, chrome: {chromedriverVersion: 96.0.4664.45 (76e4c1bb2ab46..., userDataDir: C:\Users\DELL\AppData\Local...}, goog:chromeOptions: {debuggerAddress: localhost:57541}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 74f97e7b94944b49846dacbcadffc742
*** Element info: {Using=xpath, value=//input[@name='campaignname']}
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at com.sun.proxy.$Proxy17.isDisplayed(Unknown Source)
at com.evs.vtiger.utility.WebUtil.click(WebUtil.java:78)
at com.evs.vtiger.pages.marketing.campaings.CampaingsCreatePage.enterMandetaryInfo(CampaingsCreatePage.java:24)
at com.evs.vtiger.testcases.ValidateLeadsFunctionality.validateCreateCampaings(ValidateLeadsFunctionality.java:129)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCampaings -->
        <test-method is-config="true" signature="afterTestCase()[pri:0, instance:com.evs.vtiger.testcases.ValidateLeadsFunctionality@4a7f959b]" started-at="2022-01-13T10:10:02 IST" name="afterTestCase" finished-at="2022-01-13T10:10:05 IST" duration-ms="2339" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTestCase -->
        <test-method signature="validateValidLogin(java.lang.String)[pri:0, instance:com.evs.vtiger.testcases.ValidateLeadsFunctionality@4a7f959b]" started-at="2022-01-13T10:10:05 IST" name="validateValidLogin" finished-at="2022-01-13T10:10:05 IST" duration-ms="0" status="FAIL">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method validateValidLogin requires 1 parameters but 3 were supplied in the @Test annotation.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method validateValidLogin requires 1 parameters but 3 were supplied in the @Test annotation.
at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:447)
at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:353)
at org.testng.internal.Parameters.createParameters(Parameters.java:700)
at org.testng.internal.Parameters.handleParameters(Parameters.java:884)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateValidLogin -->
        <test-method signature="validateCreateLeads()[pri:1, instance:com.evs.vtiger.testcases.ValidateLeadsFunctionality@4a7f959b]" started-at="2022-01-13T10:10:05 IST" name="validateCreateLeads" finished-at="2022-01-13T10:10:05 IST" depends-on-methods="com.evs.vtiger.testcases.ValidateLeadsFunctionality.validateValidLogin" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ValidateLeadsFunctionality.validateCreateLeads()[pri:1, instance:com.evs.vtiger.testcases.ValidateLeadsFunctionality@4a7f959b] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ValidateLeadsFunctionality.validateCreateLeads()[pri:1, instance:com.evs.vtiger.testcases.ValidateLeadsFunctionality@4a7f959b] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateLeads -->
        <test-method is-config="true" signature="afterTestCaseClass()[pri:0, instance:com.evs.vtiger.testcases.ValidateLeadsFunctionality@4a7f959b]" started-at="2022-01-13T10:10:05 IST" name="afterTestCaseClass" finished-at="2022-01-13T10:10:06 IST" duration-ms="814" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTestCaseClass -->
        <test-method is-config="true" signature="disconnectDB()[pri:0, instance:com.evs.vtiger.testcases.ValidateLeadsFunctionality@4a7f959b]" started-at="2022-01-13T10:10:06 IST" name="disconnectDB" finished-at="2022-01-13T10:10:06 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- disconnectDB -->
      </class> <!-- com.evs.vtiger.testcases.ValidateLeadsFunctionality -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
